### ISSUE TITLE
[Feature request] Please allow the use of a hostname instead of an IP address

### ISSUE THREAD

**Issue by DanielTUK** [ioBroker/ioBroker.ping#105]
**Is your feature request related to a problem? Please describe.**
I have a bunch of hosts in different rooms/buildings, that sometimes get unplugged. Since those hosts get their IP from a DHCP Server that I don't control, their IPs may change without me noticing. The config page of this plugin does not accept a hostname (FQDN) instead of an IP. Therefore I cannot use this plugin to check if the hosts are still online. 

**Describe the solution you'd like**
I would like to use hostnames of the hosts instead of their IPs. 

**Describe alternatives you've considered**
I have considered running a script every few hours to check the DNS entries of the hosts and update the configuration of this plugin if needed. But since I have not found a way to update the configuration from a script, this doesn't seem possible. Even if it is possible, it is ugly.

**Comment by Apollon77** [comment]
Did you tried to enter the hostname in the IP field? ;-)

**Comment by DanielTUK** [comment]
Yes, I did try to enter the hostname in the IP field. Unfortunately I cannot save the settings if I do that. The 'save' button does not work until I remove the hostname from the IP field.

**Comment by DanielTUK** [comment]
OK, I tried with a different computer today and it works now. So I guess the issue is caused by some combination of computer/browser+plugins/iobroker. Since I probably wont be able to provide more useful information on this issue I'm closing this. If anyone else finds this issue in the future: Try a different computer and/or browser.
