### ISSUE TITLE
Import / Export of Device List

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker.ping#110]
**Is your feature request related to a problem? Please describe.**
I have a large list of devices which I would like to maintain in Excel or a Texteditor

**Describe the solution you'd like**
Import / Export (csv) of the device list

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by cbecker2** [comment]
Hello, i'm on v1.6.2 and for me it isn't working. What could be my failure?

**Comment by axelhannemann** [comment]
where (directory) is the csv file exported to?

**Comment by Rushmed** [comment]
For me the export is also not working. Nothing happends after hitting the export button.
For theh input button a a fileselect window is opened. So far I think only export dosn`t work.

**Comment by mcm1957** [comment]
> For me the export is also not working. Nothing happends after hitting the export button. For theh input button a a fileselect window is opened. So far I think only export dosn`t work.

Please add version of
Adapter
Admin
Js-controller
Node
You are using

**Comment by GermanBluefox** [comment]
Fixed in 7.0.18 admin
