### ISSUE TITLE
keine Erkennung

### ISSUE THREAD

**Issue by AlRo75** [ioBroker/ioBroker.ping#114]
Bei allen Echo (Amazon) - Geräte und Sky-Boxen erfolgt keine Erkennung. Der Status ist immer false.

**Comment by mcm1957** [comment]
a) Please report the used revisions with every issue:

adapter:
admin:
js-controller:
node:
o/s:

b) can the corresponding device be pinged at system level (i.e. using ping command on linux)?

**Comment by Apollon77** [comment]
Does it work when you run ping on commandline? When not then the devices are configured to not answer to "Ping" trances. then no chance

**Comment by mcm1957** [comment]
@Apollon77 
As no response has been provided I suggest to close
