### ISSUE TITLE
ping has an invalid jsonConfig

### ISSUE THREAD

**Issue by 150d** [ioBroker/ioBroker.ping#123]
After modifying the device list (adding some new devices to ping, disabling/removing others, changing the order of entries) the following error appears in the log on every start of the ping adapter:

admin.0
ping has an invalid jsonConfig: 
```
[{"instancePath":"/items/_devices/items/devices","schemaPath":"#/patternProperties/%5E.%2B/allOf/22/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"export"},"message":"must NOT have additional properties"},{"instancePath":"/items/_devices","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

There don't appear to be any consequences though, all devices are pinged and all objects are created/updated.

Is there something I can do?

**Versions:**  
 - Adapter version: v1.6.2
 - JS-Controller version: v5.0.12
 - Node version: v18.17.1
 - Operating system: Linux/ubuntu

**Additional context**  
admin version: v6.12.0

**Comment by mcm1957** [comment]
seems to be a schema issue

https://github.com/ioBroker/adapter-react-v5/issues/205

Does not have any effect on functionality of adapter.

**Comment by mcm1957** [comment]
@Apollon77 
Should be labelled as BUG even it is most likely a schema error.

**Comment by GermanBluefox** [comment]
should be fixed by https://github.com/ioBroker/adapter-react-v5/blob/main/schemas/jsonConfig.json#L4865
