### ISSUE TITLE
Sort entries by IP

### ISSUE THREAD

**Issue by Kuddel071089** [ioBroker/ioBroker.ping#14]
It would be very nice to sort all entries by IP

**Comment by Apollon77** [comment]
What you mean? Where to sort which entries? 

You mean the list in Admin? Is currently always in the order you entered it.

**Comment by Kuddel071089** [comment]
All Entries in the Ping Adapter which ioBroker should Ping.

e.g.

NAS 192.168.1.10
Fritz Box 192.168.1.1

I entered the IP of the FritzBox Alter the NAS nur 1 is smaller than 10.
So it would be nice to sort it, that Fritz Box is the first entry

**Comment by Apollon77** [comment]
Again: In Admin interface when entering the IPs? or Where?

**Comment by Kuddel071089** [comment]
So jetzt mal auf deutsch :-D

Man hinterlegt doch im Ping Adapter diverse Geräte mit ihren IPs.
Jetzt wäre es doch toll, wenn man die komplette Liste der Geräte im Ping Adapter nach deren IPs sortieren könnte

**Comment by JayVee2** [comment]
Ehrlichgesagt fände ich das auch super. Einfach die Liste nach IP-Adressen sortieren. No rocket science.
Gibt's da schon einen Weg?
Von mir aus auch nach Name.
In der Praxis fügt man Geräte hinzu und löscht wieder welche und die Liste von Hand zu sortieren ist irgendwie nicht zeitgemäß.

**Comment by Apollon77** [comment]
If we sort then via IP I would prefer :-)

**Comment by JayVee2** [comment]
Perfect with me.

**Comment by JayVee2** [comment]
Ich habe mal einen Vorschlag as Pull Request gemacht..
