### ISSUE TITLE
Ping-Struktur variabel halten, Systemname/Hostname manuell anpassbar?

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.ping#164]
Momentan wird die ping-Struktur mit dem Systemnamen / Hostname angelegt.
Sobald man das Sytem wechselt und man einen anderen Namen verwendet, verwenden muss, kann man die angelegten Skripte nicht mehr nutzen, da man ja ping.0.SYSNAME.IP genutzt und der nicht mehr gültig ist.
So sollte man die Möglichkeit haben, den Systemnamen manuell in der Adapterconfig (Instanzeinstellungen) ändern zu können, so dass man wieder den alten "SYSNAME" eingeben kann und somit alle Skripte weiter laufen können.

Warum überhaupt mit Systemnamen? ping.0.ip_adresse würde doch auch reichen?

**Comment by mattreim** [comment]
> Warum überhaupt mit Systemnamen? ping.0.ip_adresse würde doch auch reichen?

Diese Funktion ist bereits vorhanden  und heißt: "No host name in state name".

![Ping-NoHOST](https://github.com/user-attachments/assets/417c7cea-d295-41cc-a3c0-b03ed3e0b7aa)
