### ISSUE TITLE
Ping with another port

### ISSUE THREAD

**Issue by davidwaze** [ioBroker/ioBroker.ping#168]
Hello

This is something "basic" but it didn't found how to ping another port such as monitoring my webserver on port 443.
Its is possible ?

Thanks

**Comment by mcm1957** [comment]
ping does not use any ports. ping uses icmp pacakte to check the reachability of a system:

see https://linux.die.net/man/8/ping

So monitoring a webserver requires some software trying to establish an tcp connection. Thats out of scope for ping.

**Comment by davidwaze** [comment]
Thanks for your answer.

Any idea if another adapter would do this ?

**Comment by mcm1957** [comment]
I donr know. I would suggest to ask at forum https///forum.iobroker.net
