### ISSUE TITLE
Sicherungspfeil für die Einstellungen einfügen

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.ping#18]
Bei anderen Adaptern gibt es einen Pfeil, wo man dann die gemachten Einstellungen als json sichern kann. Bitte auch zur Verfügung stellen.
vgl. auch:
https://forum.iobroker.net/topic/24129/adaptereinstellungen-sichern/7

**Comment by Jey-Cee** [comment]
Dürfte Teil von Admin 3 Config sein.
#8
