### ISSUE TITLE
Ver. 1.7.4 Fehlermeldung rangeLength is invalid

### ISSUE THREAD

**Issue by Norb1204** [ioBroker/ioBroker.ping#184]
Bei der Version 1.7.4 kommt eine Fehlermeldung:
Object ping.0.browse.rangeLength is invalid: Default value has to be type "number" but received type "string"

**Comment by Apollon77** [comment]
Wo genau kommt die Meldung? Bitte mehr Detaisl, mooaaarrrr log

**Comment by Norb1204** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/a0b87cba-026e-4e0d-9907-94cac4a40f70">

**Comment by Norb1204** [comment]
Danke
