### ISSUE TITLE
Version 1.7.8 does not start

### ISSUE THREAD

**Issue by diamand2k22** [ioBroker/ioBroker.ping#188]
Same problem as v1.7.7

`host.pi4b | 2024-09-29 19:21:04.270 | info | Restart adapter system.adapter.ping.0 because enabled
-- | -- | -- | --
host.pi4b | 2024-09-29 19:21:04.270 | error | instance system.adapter.ping.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.pi4b | 2024-09-29 19:21:04.270 | error | Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.ping/main.js:858:16)
host.pi4b | 2024-09-29 19:21:04.270 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'init')
host.pi4b | 2024-09-29 19:21:04.269 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
`

**Comment by Horgul123** [comment]
Can confirm the issue

**Comment by Matzebhv** [comment]
Confirm!

**Comment by tmaul1968** [comment]
confirmed, rolled back to 1.7.6

**Comment by Negalein** [comment]
same here
1.7.6 works

**Comment by mcm1957** [comment]
Just for info - problem is under investigation

**Comment by fresenbruch** [comment]
same here

**Comment by amg666** [comment]
1.7.9 works fine , thx :-)

**Comment by Negalein** [comment]
> 1.7.9 works fine , thx 👍

same here
