### ISSUE TITLE
Alle Ziele immer 'false'

### ISSUE THREAD

**Issue by WaJoWi** [ioBroker/ioBroker.ping#19]
Seit ich unter Proxmox von einer VM auf einen Container (Debian Buster) umgestellt habe, bekomme ich den Ping-Adapter nicht zum Laufen. Also laufen tut er schon, doch meldet er bei jeder Adresse, dass sie nicht erreichbar ist.

Siehe auch: https://forum.iobroker.net/topic/24957/ping-adapter-meldet-immer-false

Since I switched from a VM to a container (Debian Buster) under Proxmox, I can't get the ping adapter to work. So it is already running, but it reports that every address is unreachable.

See also: https://forum.iobroker.net/topic/24957/ping-adapter-meldet-immer-false

---

**System data:**

Model: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM: 7.67 GB
Node.js: v10.16.3
NPM: 6.9.0
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
JS-Controller (1): 1.5.14
Admin: 3.6.4
PING Adapter: 1.3.2

> *created by ioBroker.info*

**Comment by WaJoWi** [comment]
Lösung: `sudo apt-get install iputils-ping --reinstall`

**Comment by zaphod2** [comment]
Danke, damit gehts.
