### ISSUE TITLE
Missing rooms from CCU in selection list

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.ping#22]
The rooms selection list doesn't list all rooms defined in CCU. Especially changes seem not to be updated.
CCU3 and iobroker already rebooted. Adapter restarted.
Any idea?
-jayvee

**Comment by Apollon77** [comment]
What this has to do with the ping adapter? Created issue in wrong repository?

**Comment by JayVee2** [comment]
The ping adapter allows in column 3 of the ip address list to assign a room to each ip address.

I'm using the adapter to verify my whole IT infrastructure and create a live HTML report from this to be shown in vis/mediola. If a significant device is not responsive I'm sending an TTS message to sonos/alexa. ping adapter works fine for me to detect unstable WLAN devices or unintential LAN unplugging in combination with an add-on script.

BUT: In the meantime I have 36 IP addresses to be checked (heating gateways, broadlink IRs, gosunds, alexas, sonos' ...). It is useful to assign a room to each IP address in the list for clarity.

AND: As written in another thread, it would be great if the list of IP addresses would be sorted by either name or IP address (anthing fine to me). Currently the order is given by order of input.

**Comment by Apollon77** [comment]
Ok so Tobias about that the room list imported from cpu is not up to date in iobroker? Then still wrong repo because hm-rega is responsible to sync names and rooms with ccu when i remember correctly. Do still not ping ;-))

Alternatively just add rooms by yourself by using enums page in iobroker.

**Comment by JayVee2** [comment]
Thanks for the hint with the enum page.
I understand it's rega adapter problem, not a ping adapter problem.

However as this is a ping thread, is it very difficult to a professional like you add an automatic sort to the ip address table on save? No user interface required at all. The next time it shows up it's shown sorted. That would solve it.

**Comment by Apollon77** [comment]
There is an extra issue for this correct ? ;-)

**Comment by JayVee2** [comment]
Yes, #14 
[https://github.com/ioBroker/ioBroker.ping/issues/14](url)

**Comment by JayVee2** [comment]
Yes, #14 [](https://github.com/ioBroker/ioBroker.ping/issues/14)

**Comment by Apollon77** [comment]
As soon as someone finds time it can be taken care of ... I would more sort by IP instead of name ... but effectively ... time is an issue.

We also take PRs ;-)

**Comment by JayVee2** [comment]
PRs?

**Comment by Apollon77** [comment]
Pull request. ... if you can write JavaScript Code, Change it yourself and propose the change ;-)

**Comment by JayVee2** [comment]
So I did with other JS projects. But I haven’t started with IoBroker adapter programming yet and I don’t properly understand the code how the table is saved after editing.
I already thought about an extension of the ping adapter with my HTML table I posted in the other thread.

**Comment by Apollon77** [comment]
Sorting could be done in admin/index.html and index_m.html in the save method. Most likely at the end before the callback is called.

**Comment by Apollon77** [comment]
For this no iobroker knowledge is needed. Just Browser JavaScript ;-)

**Comment by JayVee2** [comment]
Where is index_m.html?

**Comment by Apollon77** [comment]
If not in admin dir then ignore.

**Comment by JayVee2** [comment]
Seems not to be that easy. When I update ../files/ping.admin/index.html on Pi, changes are not shown in browser. Even changes to labels are not shown. Deleting index.html provides error message.
Restarting the adapter also makes no change. Seems to take index.html from somewhere else??

**Comment by JayVee2** [comment]
>>We also take PRs ;-)

So, I did. What's next?

**Comment by Apollon77** [comment]
As soon as Bluefox or me find time we will review it, comment or accept the change and release a new version. :-)
