### ISSUE TITLE
[feature request] change ping intervall with a state

### ISSUE THREAD

**Issue by mar565** [ioBroker/ioBroker.ping#24]
It would be nice to have an object that allows to change the ping intervall by script. Could you add this feature?

**Comment by Apollon77** [comment]
Can you describe your usecase please that we better understand why this would be a required feature?

**Comment by m-s-b** [comment]
I´m not sure if it´s the same as @mar565 requests, but it would be great to have for each host a state with the polling interval. So you can use different ping intervalls for ech host and you have the possibility to change the intervall with a script.

**Comment by Apollon77** [comment]
Ok, but still: why?

**Comment by m-s-b** [comment]
Why, part 1
I use the ping adapter to chek via 8.8.8.8 if internet connection within a short period. 
I also check VPN Tunnel for two different locations. For that I don´t need a short period. But using a seperate instances needs RAM... 
Why part 2:
When I´m not at Home Ping result for VPN Tunnel ist not so interesting, so intervall could be enlarged while absent...
