### ISSUE TITLE
Ping Timeout

### ISSUE THREAD

**Issue by Alveran81** [ioBroker/ioBroker.ping#25]
Hallo,

kann man irgendwo das Ping Timeout definieren? Hintergrund ist der das ich einige per LTE/VPN aufgeschaltete Stationen überwache und der erste Ping meist länger als eine Sekunde unterwegs ist.

**Comment by JuniperChris929** [comment]
Entweder timeout erhöhen oder die Möglichkeit, nach "mehreren" Pingverlusten erst als "offline" gewertet zu werden. Besonders im WLAN kann so ein ping mal flöten gehen - einzelne pings sind nicht die Ultra-Prio für einen Router, daher wäre es schon besser, dass mindestens x (z.B. 5 wie bei windows) pings verloren gehen müssen, damit man definitiv weiß, dass das Gerät jetzt offline ist

**Comment by basti4557** [comment]
@JuniperChris929 https://github.com/ioBroker/ioBroker.ping/pull/48

**Comment by JuniperChris929** [comment]
GENIAL!!!!!!!!
1000 Dank :)

**Comment by Alveran81** [comment]
Thank you very much. :-)

**Comment by Alveran81** [comment]
Hallo,
habe soeben auf Version 1.5.1 geupdatet. Bekomme folgende Fehler im Log:
`<html>
<body>


host.IOBroker | 2022-01-20 09:34:32.296 | info | Restart adapter system.adapter.ping.0 because enabled
-- | -- | -- | --
host.IOBroker | 2022-01-20 09:34:32.295 | error | instance system.adapter.ping.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IOBroker | 2022-01-20 09:34:32.295 | error | Caught by controller[0]: at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
host.IOBroker | 2022-01-20 09:34:32.295 | error | Caught by controller[0]: at ChildProcess.emit (domain.js:475:12)
host.IOBroker | 2022-01-20 09:34:32.295 | error | Caught by controller[0]: at ChildProcess.emit (events.js:400:28)
host.IOBroker | 2022-01-20 09:34:32.295 | error | Caught by controller[0]: at ChildProcess.<anonymous> (/opt/iobroker/node_modules/iobroker.ping/lib/ping.js:144:25)
host.IOBroker | 2022-01-20 09:34:32.295 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.ping/main.js:105:150
host.IOBroker | 2022-01-20 09:34:32.294 | error | Caught by controller[0]: ReferenceError: numberOfRetries is not defined
ping.0 | 2022-01-20 09:34:32.065 | error | numberOfRetries is not defined
ping.0 | 2022-01-20 09:34:32.065 | error | ReferenceError: numberOfRetries is not defined at /opt/iobroker/node_modules/iobroker.ping/main.js:105:150 at ChildProcess.<anonymous> (/opt/iobroker/node_modules/iobroker.ping/lib/ping.js:144:25) at ChildProcess.emit (events.js:400:28) at ChildProcess.emit (domain.js:475:12) at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
ping.0 | 2022-01-20 09:34:32.064 | error | uncaught exception: numberOfRetries is not defined
ping.0 | 2022-01-20 09:34:30.028 | info | starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.ping, node: v14.18.3, js-controller: 3.3.22


</body>
</html>`

Auch wenn ich die Anzahl der Retries ändere bekomme ich die gleiche Fehlermeldung.

**Comment by Apollon77** [comment]
fixes come soon
