### ISSUE TITLE
Minimum JS-Controller dependency is too low

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.ping#27]
The adapter crashes because adapter-core cannot find exitCodes.js
==> https://forum.iobroker.net/topic/36196/fehlermeldung-module-js-550/2

Raise the minimum version of JS-Controller in io-package.json to one that contains exitCodes.js

**Comment by Apollon77** [comment]
WHich adapter-core added the exitCode dep? I thought 2.4.0? Or?

**Comment by AlCalzone** [comment]
Doesn't matter, adapter-core does not enforce the correct js-controller version.

**Comment by AlCalzone** [comment]
According to https://github.com/ioBroker/ioBroker.js-controller/commit/899caa2d399c0214bd4d92d78cff61477b4cba73, exitCodes.js was added in 1.5.8.
