### ISSUE TITLE
missing values for time and rps

### ISSUE THREAD

**Issue by gidhap** [ioBroker/ioBroker.ping#29]
Reading pull requests #9 & #10 I expected to get datap for:

time -- number, value.interval -- time of ping in seconds
rps -- number, value -- number of round trips to host per second

However none of them exits, am I wrong or is this a bug ?
![grafik](https://user-images.githubusercontent.com/28500973/98898917-efbd4480-24ae-11eb-974d-87482d566093.png)
![grafik](https://user-images.githubusercontent.com/28500973/98898969-08c5f580-24af-11eb-8080-052569fa7318.png)
Thanks

**Comment by stephan1827** [comment]
Same issue here, I dont see any ping values
