### ISSUE TITLE
State value to set for "x" has to be type "number" but recevied type "string"

### ISSUE THREAD

**Issue by simonssoftware** [ioBroker/ioBroker.ping#36]
**Describe the bug**  
![image](https://user-images.githubusercontent.com/50638485/119769761-58a06300-bebb-11eb-95b6-164c2d038a86.png)

![image](https://user-images.githubusercontent.com/50638485/119770902-209a1f80-bebd-11eb-95da-83353aa852eb.png)

**To Reproduce**  
1. Add a device which is not reachable
2. Turn on extended information

**Expected behavior**  
Do not set value '-' when device is not reachable.

**Versions:**  
 - Adapter version:  1.4.12
 - JS-Controller version: 3.3.8
 - Node version: 12.20.1
 - Operating system: Linux

**Comment by Baenker** [comment]
Wenn ich es richtig sehe muss die Zeile 105 der main.js angepasst werden:

`adapter.setState(task.stateTime, {val: result.ms === null ? '-' : result.ms / 1000, ack: true});`

ich würde vermuten besser wäre:

`adapter.setState(task.stateTime, {val: result.ms === null ? 0 : result.ms / 1000, ack: true});`

**Comment by Apollon77** [comment]
then "null" is the better value (so not as string but null). Adapter is only list will come to it soon :-)

**Comment by Apollon77** [comment]
fixed in next version
