### ISSUE TITLE
saving with active filter

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker.ping#4]
when saving with an active filter for a room results in lost of all entered devices of other rooms. I didn't test the other filters - but I guess it results in the same problem.

**Comment by GermanBluefox** [comment]
I am working on it:
![image](https://cloud.githubusercontent.com/assets/4582016/21966743/83c51d48-db79-11e6-9c22-7db4f92db718.png)
Will be possible with next admin+ping (everything on github)

**Comment by GermanBluefox** [comment]
@Goersch please test and close
