### ISSUE TITLE
Seit dem Update Error Meldungen vom Adapter: Error: ping.probe: there was an error while executing the ping program. check the path or permissions...: Error: spawn /bin/ping ENOENT

### ISSUE THREAD

**Issue by Hohenbostler** [ioBroker/ioBroker.ping#42]
Mein aktuelles System : 

    Plattform: linux
    Betriebssystem: linux
    Architektur: x64
    CPUs: 2
    Geschwindigkeit: 2001 MHz
    Modell: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
    RAM: 9.5 GB
    System-Betriebszeit: 13 T. 09:04:09
    Node.js: v12.22.6
    Datenträgergröße: 3572.6 GB
    Festplatte frei: 1978.1 GB
    Adapter-Anzahl: 360
    NPM: v6.14.15
    Betriebszeit: 02:02:23
    Aktive Instanzen: 29
    Pfad: /opt/iobroker/

Seit dem Update vom iobroker Image im Docker habe ich folgende Fehlermeldung: 

Error: ping.probe: there was an error while executing the ping program. check the path or permissions...: Error: spawn /bin/ping ENOENT

**Comment by Apollon77** [comment]
Ist denn ping installiert und verfügbar? Ggf Paket installieren?

**Comment by Hohenbostler** [comment]
Wie meinst du das installiert ?  Der ing adapter lief vor dem Update Monatelang problemlos
. ich wüsste nicht was ich da machen müsste

**Comment by Apollon77** [comment]
Der Oing adapter nutzt das "ping" binary von der loakelan installation unter Linux. Wenn also "/bin/ping" nicht da ist dann geht es nicht. ping ist in irgendeinem debial Paket drin und wenn das nicht im Container installiert ist dann hast Du kein ping. Wenn bitte ggf beim Docker container issue öffnen wenn es mal da war und jetzt nicht mehr ...
