### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by KrX3D** [ioBroker/ioBroker.ping#43]
Hello,

since today im getting this Error:

`
<html>
<body>

Error: ping.probe: there was an error while executing the ping program. check the path or permissions...: Error: spawn /bin/ping ENOENT
--

</body>
</html>`

im using iobroker in docker on my NAS. Ping version is 1.5.0

I didnt change anything in the last days but im getting now since some hours a massive amount of this errors

**Comment by Apollon77** [comment]
Then make sure that the "Ping" linux package/command is installed and available in your container
