### ISSUE TITLE
Verschieben Pingintervall je nach Erreichbarkeit 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.ping#45]
Hallo,

ich fände es ziemlich praktisch, wenn man ja nach Erreichbarkeit eines Gerätes einen anderen Intervall zum pingen einstellen könnte.

Zb wenn das Gerät nicht erreichbar ist alle 3sek.
Wenn man zuletzt einen erfolgreichen ping hatte nur jede Minute.
Oder wie man es sich eben wünscht.

Eventuell sogar pro Gerät einstellbar. 

Mein Gedanke ist, dass man wenn man zu Hause ist ja nicht das Netz und Handy andauernd belasten muss.
Wenn man das Haus verlässt und wieder nach Hause kommt wird aber schnell das Handy wieder gefunden da es öfters angepingt wird.

**Comment by mcm1957** [comment]
Implemented at 1.6.2
https://github.com/ioBroker/ioBroker.ping#162-2023-07-19

@Apollon77 
can be closed
