### ISSUE TITLE
Update from 1.5.0 to 1.5.1 / how ?

### ISSUE THREAD

**Issue by erwini** [ioBroker/ioBroker.ping#53]
**Describe the bug**  
Runing Ping version 1.5.0 on iobroker.

Interesting in feature added to 1.5.1

No knob to update to 1.5.1 provided.

Noticed here on gitpage: Marked as : Test and release failing.

**Expected behavior**  
Update possablity on iobroker UI to 1.5.1

How can it be solved ? Manual Installation ? If yes, how ?

**Comment by Apollon77** [comment]
Seems that 1.5.1 neverwent out ... I have started the release again ...

**Comment by Apollon77** [comment]
Ok, good that it failed ... is buggy ... I will check and fix soon, then we will have an 1.5.2
