### ISSUE TITLE
ping per Javascript ausführen

### ISSUE THREAD

**Issue by Baenker** [ioBroker/ioBroker.ping#93]
Ich fände es schön wenn es möglich wäre bestimmte IP,´s aus einen Javascript direkt anzupingen. Ich überwäche mit dem Adapter ein paar IP´s. I. d. R. laufen die immer alle. Um nicht unnötig oft zu pingen habe ich einen relativ langen Intervall von 10 Minuten eingestellt.

Jetzt habe ich aber den Anwendungsfall, dass wenn ein Datenpunkt von einen anderen Adapter auf false geht würde ich gerne direkt zwei Datenpunke aus dem Ping Adapter aktualisieren ohne erst den nächsten Intervall abzuwarten.

**Comment by GermanBluefox** [comment]
It is possible with:
```
sendTo('ping.0', 'ping', '192.168.1.1', (res) => {
    console.log('Result: ' + JSON.stringify(res)); // Result: {"result": {"host": "192.168.1.1", "alive": true, "ms": 250}} 
});
```

**Comment by Baenker** [comment]
Super das es umgesetzt werden soll! Vielen Dank. Habe es gerade getestet aber es passiert nichts. Im Log kommt gar nichts. Kein Fehler kein nix.

`function func_test(){

log('Starte Test');

sendTo('ping.0', 'ping', '192.168.178.1', (res) => {
    log('Result: ' + JSON.stringify(res)); // Result: {"result": {"host": "192.168.1.1", "alive": true, "ms": 250}} 
});

}

func_test(); `

die IP ist die Adresse von der Fritzbox diese wird auch von ping.0 überwacht.

Bei dem Script oben kommt nur der Log von oben drüber „Starte Test“.

**Comment by Apollon77** [comment]
Welche version hast du denn versucht? Muss mindestens 1.6.1 sein, besser 1.6,2

**Comment by Baenker** [comment]
getestet mit der 1.62. Sind noch andere Adapter relevant? z.B. Web oder js-controller? Dort habe ich noch die Stable Version und würde dort aber auch nicht auf dem Beta-Zweig wechseln. Und wenn es bei Dir läuft ist es wohl ein Einzelschicksal bei mir.

**Comment by Sascha8** [comment]
geht hier auch nicht mit frisch aufgesetztem System. Bitte mal fixen oder den Hinweis auf sendTo rausnehmen.

**Comment by mcm1957** [comment]
@Apollon77 
fixed sollte weg und bug dazu

**Comment by klein0r** [comment]
> Im Log kommt gar nichts. Kein Fehler kein nix.

Wenn ich mir den Code anschaue, ist das wohl aktuell richtig. Der Callback wird nur im Fehlerfall aufgerufen und man bekommt auf diesem Weg nie ein Ergebnis geliefert. Das führt im aktuellen JavaScript-Adapter auch zu Timeouts (weil nie geantwortet wird).
